In [1]:
import pandas as pd
import geopandas as gpd
import osmnx as ox
import matplotlib.pyplot as plt

In [105]:
gdf = gpd.read_file('./pedestrian-safety-2014/pedestrian-safety-2014.shp')
survey = pd.read_csv('Newport Pedestrian Safety Survey - May 2014 cleaned.csv')

In [106]:
# drop unused columns
slim_survey = survey.drop(['Collector ID', 'Start Date', 'End Date', 'Comment/Explanation'], axis=1)

# make the columns line up with intersection ids
column_names = [
    'Respondent ID',
                1,1,1,
                2,2,2,
                3,3,3,
                4,4,4,
                5,5,5,
                6,6,6,
                7,7,7,
                8,8,8,
                9,9,9,
                10,10,10,
                11,11,11,
                12,12,12,
                13,13,13,
                14,14,14,
                15,15,15,
                16,16,16,
                17,17,17,
                18,18,18,
                19,19,19,
                20,20,20,
                21,21,21,
                22,22,22,
                23,23,23,
                24,24,24,
                25,25,25
                ]
slim_survey.columns = column_names

gdf['Safe']=""
gdf['Unsafe']=""
gdf["I don't know."]=""
gdf

    id                                      geometry Safe Unsafe I don't know.
0    1  POINT (-71.31159975783214 41.50792163382231)
1    2   POINT (-71.30795507872978 41.5075726847703)
2    3  POINT (-71.30169157668472 41.50598751268677)
3    4  POINT (-71.30710260670982 41.49865626332756)
4    5    POINT (-71.30935118227099 41.493963557599)
5    6  POINT (-71.31173160202168 41.49181256414439)
6    7  POINT (-71.31209281897929 41.49148517397211)
7    8  POINT (-71.31267076611148 41.48954650321857)
8    9  POINT (-71.30688045828089 41.48339865277515)
9   10   POINT (-71.30866848222109 41.4837179657074)
10  11  POINT (-71.31308977778231 41.48434035079855)
11  12   POINT (-71.3147152540916 41.48452977116146)
12  13  POINT (-71.30953901508894 41.48771871513412)
13  14  POINT (-71.30880393858018 41.48588681656712)
14  15  POINT (-71.30849690416622 41.48278302382474)
15  16  POINT (-71.31703246087469 41.49863056191604)
16  17   POINT (-71.3172103602263 41.49083850587753)
17  18  POINT (-71.31702613957792 41.48986849163211)
18  19  POINT (-71.31523992172251 41.48687718470558)
19  20  POINT (-71.31514600531352 41.48629811883416)
20  21  POINT (-71.31497262117387 41.48696377354996)
21  22  POINT (-71.31469087194692 41.48426728851057)
22  23  POINT (-71.31404068142322 41.47684156561854)
23  24  POINT (-71.31368668880475 41.47291457303684)
24  25  POINT (-71.31493649947811 41.47143140160818)

In [103]:
pd.DataFrame(slim_survey.stack())

                               0
0   Respondent ID     4692619912
    8                     Unsafe
1   Respondent ID     4680235760
    1                     Unsafe
    2                       Safe
    4                       Safe
    5                       Safe
    6                       Safe
    7                       Safe
    8                       Safe
    9                       Safe
    10                      Safe
    11                      Safe
    12                    Unsafe
    13                      Safe
    14                      Safe
    15                      Safe
    16                      Safe
    17                      Safe
    18                      Safe
    19                      Safe
    20                    Unsafe
    21                      Safe
    22                      Safe
    23                      Safe
    24                      Safe
    25                      Safe
2   Respondent ID     3428074483
    1                     Unsafe
    2                     Unsafe
...                          ...
253 Respondent ID     3195260970
    1                     Unsafe
    2                       Safe
254 Respondent ID     3195200480
255 Respondent ID     3195159768
256 Respondent ID     3195133525
    1              I don't know.
    2              I don't know.
    3              I don't know.
    4              I don't know.
    5                       Safe
    6                       Safe
    7                       Safe
    8                     Unsafe
    9                       Safe
    10                    Unsafe
    11                    Unsafe
    12                    Unsafe
    13                      Safe
    14                      Safe
    15                      Safe
    16             I don't know.
    18                      Safe
    19                      Safe
    20                      Safe
    21                    Unsafe
    22                    Unsafe
    23                    Unsafe
    24             I don't know.
    25             I don't know.

[6175 rows x 1 columns]

In [81]:
# melt the dataframe and drop NA responses
melted_slim = pd.melt(slim_survey, id_vars=['Respondent ID']).dropna()
melted_slim

       Respondent ID variable          value
38        3271333302        1           Safe
39        3271032563        1           Safe
78        3265464670        1           Safe
83        3265142076        1           Safe
93        3261470801        1           Safe
120       3244462351        1           Safe
165       3227858407        1           Safe
168       3226325188        1           Safe
180       3224646415        1           Safe
193       3224490099        1           Safe
196       3224453264        1           Safe
199       3224442004        1           Safe
200       3224413207        1           Safe
202       3224403579        1           Safe
208       3224383665        1           Safe
215       3223661354        1           Safe
226       3223156347        1           Safe
258       4680235760        1         Unsafe
259       3428074483        1         Unsafe
263       3297418048        1         Unsafe
264       3295597866        1         Unsafe
266       3286207500        1         Unsafe
267       3286138692        1         Unsafe
270       3284706662        1         Unsafe
275       3280890138        1         Unsafe
276       3280862463        1         Unsafe
281       3279314777        1         Unsafe
283       3279072301        1         Unsafe
284       3279043489        1         Unsafe
285       3279030658        1         Unsafe
...              ...      ...            ...
19182     3227969697       25  I don't know.
19184     3226994444       25  I don't know.
19188     3225718200       25  I don't know.
19189     3225634245       25  I don't know.
19192     3225268299       25  I don't know.
19194     3224875208       25  I don't know.
19199     3224606717       25  I don't know.
19200     3224598902       25  I don't know.
19201     3224582992       25  I don't know.
19203     3224547903       25  I don't know.
19205     3224546221       25  I don't know.
19206     3224542483       25  I don't know.
19209     3224520770       25  I don't know.
19210     3224516192       25  I don't know.
19211     3224490099       25  I don't know.
19217     3224442004       25  I don't know.
19228     3224078257       25  I don't know.
19229     3224017989       25  I don't know.
19234     3223621254       25  I don't know.
19244     3223156347       25  I don't know.
19248     3223115587       25  I don't know.
19250     3223043391       25  I don't know.
19252     3223030228       25  I don't know.
19254     3222965081       25  I don't know.
19257     3222897544       25  I don't know.
19260     3222856542       25  I don't know.
19263     3222808771       25  I don't know.
19264     3222806013       25  I don't know.
19268     3222759886       25  I don't know.
19274     3195133525       25  I don't know.

[5918 rows x 3 columns]

In [113]:
grouped = melted_slim.groupby('variable')

pd.merge(gdf[gdf['id']==2],pd.DataFrame(grouped.get_group(2).value.value_counts()).T)

Empty GeoDataFrame
Columns: [id, geometry, Safe, Unsafe, I don't know.]
Index: []

In [ ]:
cleaned = pd.DataFrame(columns = ['Respondent ID',1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
for i in range(1,26):